# Use the latest LTS version of Node.js
FROM node:19-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
#Isso garante que somente os arquivos de dependências sejam copiados primeiro e as dependências sejam instaladas. Esse padrão é útil para aproveitar o cache do Docker, evitando reinstalar dependências desnecessariamente quando apenas o código fonte muda.

# Copy the rest of your application files
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Define the command to run your app
CMD ["npm", "start"]

